<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-27T17:31:43 EET" name="Default suite" finished-at="2024-08-27T17:31:47 EET" duration-ms="3566">
    <groups>
    </groups>
    <test started-at="2024-08-27T17:31:43 EET" name="Default test" finished-at="2024-08-27T17:31:47 EET" duration-ms="3566">
      <class name="databaseTesting.myTestCases">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:databaseTesting.myTestCases@5f2606b]" started-at="2024-08-27T17:31:43 EET" name="mySetup" finished-at="2024-08-27T17:31:44 EET" duration-ms="328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="AddDataToTheDatabase()[pri:1, instance:databaseTesting.myTestCases@5f2606b]" started-at="2024-08-27T17:31:44 EET" name="AddDataToTheDatabase" finished-at="2024-08-27T17:31:44 EET" duration-ms="504" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '600' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '600' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1537)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2384)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1410)
at databaseTesting.myTestCases.AddDataToTheDatabase(myTestCases.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddDataToTheDatabase -->
        <test-method signature="update()[pri:2, instance:databaseTesting.myTestCases@5f2606b]" started-at="2024-08-27T17:31:44 EET" name="update" finished-at="2024-08-27T17:31:44 EET" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- update -->
        <test-method signature="GetData()[pri:3, instance:databaseTesting.myTestCases@5f2606b]" started-at="2024-08-27T17:31:44 EET" name="GetData" finished-at="2024-08-27T17:31:47 EET" duration-ms="2690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetData -->
        <test-method signature="Delete()[pri:4, instance:databaseTesting.myTestCases@5f2606b]" started-at="2024-08-27T17:31:47 EET" name="Delete" finished-at="2024-08-27T17:31:47 EET" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Delete -->
      </class> <!-- databaseTesting.myTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
